### ISSUE TITLE
the environment is lack of action space

### ISSUE THREAD

**Issue by ifgovh** [Johann-Huber/qd_grasp#1]
(qdg) node18 ~/qd_grasp $ python3 run_qd_grasp.py -a me_scs -r kuka_wsg50 -o ycb_power_drill -nbr 2000
pybullet build time: Nov 28 2023 23:51:11
argv[0]=
n_stabilization_steps= 700
dir_path = /home/guozhang/qd_grasp/gym_envs/gym_envs/envs/src/bullet_simulation
trying to save =  /home/guozhang/qd_grasp/tmp/init_state.bullet_34373
init_state_p_local_pid_file=/home/guozhang/qd_grasp/tmp/init_state.bullet_34373 successfully saved.
Traceback (most recent call last):
  File "run_qd_grasp.py", line 15, in <module>
    ENV, EVAL_KWARGS, MULTICORE_SHARED_CFG = initialize_cpu_multicore_data()
  File "/home/guozhang/qd_grasp/utils/args_processor.py", line 359, in initialize_cpu_multicore_data
    ENV = gym.make(**ENV_KWARGS)  # Initialize env for each parallel worker
  File "/home/guozhang/anaconda3/envs/qdg/lib/python3.8/site-packages/gym/envs/registration.py", line 669, in make
    env = PassiveEnvChecker(env)
  File "/home/guozhang/anaconda3/envs/qdg/lib/python3.8/site-packages/gym/wrappers/env_checker.py", line 20, in __init__
    assert hasattr(
AssertionError: The environment must specify an action space. https://www.gymlibrary.dev/content/environment_creation/

**Comment by ifgovh** [comment]
python 3.8
I followed the install step but found gym==0.21.0 could not be installed so I installed the newest version.

(qdg) node18 ~/qd_grasp $ pip install gym==0.21.0
Collecting gym==0.21.0
  Downloading gym-0.21.0.tar.gz (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 23.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in gym setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Johann-Huber** [comment]
Hi,

Sorry for the late answer. The problem comes from setuptools. The latest versions aren't compatible with gym install (see [this post](https://stackoverflow.com/questions/77124879/pip-extras-require-must-be-a-dictionary-whose-values-are-strings-or-lists-of ) and [that one](https://github.com/readthedocs/readthedocs.org/issues/10286)).

Installing an earlier version of setuptools fixes the issue.

The installing procedure has been updated to avoid this problem (commits 951261b373648f52803d03ed68952518f6ca4ed0 and b958b64906c2cefe5d18a874870f8a1a01759fdd).

Tell me if it still persists.
